branch-defaults:
  master:
    environment: PassingBy-worker
environment-defaults:
  PassingBy-env-1:
    branch: null
    repository: null
global:
  application_name: passing-by
  default_ec2_keyname: null
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: passing-by
  sc: git
  workspace_type: Application
