branch-defaults:
  master:
    environment: Passingby-prod
environment-defaults:
  Passingby-prod:
    branch: null
    repository: null
global:
  application_name: passing-by-prod
  default_ec2_keyname: null
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: passing-by-prod
  sc: git
  workspace_type: Application
